### ISSUE TITLE
Only 750 frames are processed

### ISSUE THREAD

**Issue by A-2-H** [xg-chu/lightning_track#2]
Why only 750 frames is processed?
Can we change the limit to make longer videos?

**Comment by xg-chu** [comment]
I have no idea why only 750 frames is processed...
The visualize length is limited to **_300_** frames, but all the frames is processed actually.🧐

**Comment by xg-chu** [comment]
BTW, this may change the frame numbers, please also check this.

> lightning_track/engines/core_engine.py: line 46-48
> if meta_data['video_fps'] > 50:
                    if fidx % 2 == 0:
                        continue
