### ISSUE TITLE
Head moves in the tracked output even when the input video head is static.

### ISSUE THREAD

**Issue by Jeshurun-Edward** [xg-chu/lightning_track#4]
Appreciate the wonderful work in this repository. It's ease of use and control is quite good.

I have been trying to do tracking on some custom videos, the output expressions seem to work well, but I see that there is some movement in the head even when the original video has no head movement, attaching a clip for reference, I tried smoothing the EMOCA pose and expression too but still I observe this in the output. I'm not sure if I'm missing something with regards to the preprocessing or how the video must be recorded. It will be helpful if I'm directed on how to get more stable outputs.

Thank you once again!

https://github.com/xg-chu/lightning_track/assets/37731078/b2a0bb17-a5d4-4c40-811e-b51f58eaca46

**Comment by xg-chu** [comment]
Unfortunately, some head shaking is unavoidable at present, generally the metrical-tracker performs better in terms of head pose smoothing.
